### ISSUE TITLE
gstatus is not compatible with this version of glusterfs 4.1.2

### ISSUE THREAD

**Issue by Metrax** [gluster/gstatus#11]
Hi,

please fix this Version compatibility problem.

`#gstatus -a -o json
gstatus is not compatible with this version of glusterfs 4.1.2`

I'm using the latest git version.

Thank you!

**Comment by tkriviradev** [comment]
+1

**Comment by Apollon77** [comment]
me too :-(

**Comment by sac** [comment]
@Metrax @tkriviradev @Apollon77 gstatus is deprecated not supported on glusterfs 4.x. However, there is some work on better monitoring tools, will keep posted.

**Comment by Apollon77** [comment]
that would be awesome!

**Comment by ruanling** [comment]
I deleted the version check, some functions work well on version 4.1.5

**Comment by Apollon77** [comment]
And which? Which not? ;-) do you have more Details?

**Comment by vholer** [comment]
@sac If the tool is deprecated, what's the successor? Thank you.

**Comment by sac** [comment]
> @sac If the tool is deprecated, what's the successor? Thank you.

@vholer we have Prometheus and Grafana integration planned.

**Comment by Apollon77** [comment]
I did not planned to use Prometeus just to monitor my Gluster installation. SO please provide something more generic like this script.
Not only enterprise/business are using GlusterFS, please keep that in mind! And in general: To urge a user to use such a tool just because of this feels not right

**Comment by markebbers** [comment]
I just updated a test cluster from GlusterFS 3.8.8 --> 6.1-1 and because of that lost the gstatus support, which we use for monitoring, but still got it to work;

1. gstatus/gstatuscfg/config.py update min_version to 6.1
2. gstatus is working again. Tested with a node down and it showed 'UNHEALTHY'.

**Comment by Apollon77** [comment]
I use it the same with glusterfs 5.6 ... So why not chaning the code in a way that it can be used again officially?

**Comment by amarts** [comment]
> > @sac If the tool is deprecated, what's the successor? Thank you.
> 
> @vholer we have Prometheus and Grafana integration planned.

Sorry for delay. We wanted to keep https://github.com/gluster/gluster-prometheus as a possible next step.

We will announce in mailing list when a 'decent' monitoring tool is ready.

**Comment by Apollon77** [comment]
I think it was said in an other thread, but prometheus is not that common beside the enterprise segment (my opinion). i think for many more private or SMB installations this would net really be an option ... that python script is easy and without dependecies to other tech

**Comment by sac** [comment]
Fixed in this bulid: https://copr.fedorainfracloud.org/coprs/sac/gstatus/builds/ should resolve this issue.
