### ISSUE TITLE
Make a release

### ISSUE THREAD

**Issue by vitlav** [gluster/gstatus#16]
Please, make a new release of the code, with new version, new tag  and new tarball for that new tag.

**Comment by sac-urs** [comment]
> Please, make a new release of the code, with new version, new tag and new tarball for that new tag.

@vitlav I've pushed the new tag: https://github.com/gluster/gstatus/archive/v0.65.tar.gz
ref: https://github.com/gluster/gstatus/releases

I would like to add that, we have not tested the recent commits, since the support of gstats
has been dropped since a couple of years.

**Comment by sac** [comment]
Done. v0.66 can be downloaded from: https://copr.fedorainfracloud.org/coprs/sac/gstatus/builds/

**Comment by vitlav** [comment]
> Done. v0.66 can be downloaded from: https://copr.fedorainfracloud.org/coprs/sac/gstatus/builds/
tag v0.66 is missed at
https://github.com/gluster/gstatus/tags

**Comment by sac** [comment]
Thanks. Pushed the tags now.
