### ISSUE TITLE
Latest commit "buggy version check" leaves spurios else:

### ISSUE THREAD

**Issue by s-seitz** [gluster/gstatus#20]
Hi!

The latest gstatus commit removes an if: before main() but not the else: which leads to a syntax error.

**Comment by amarts** [comment]
@sac is it possible to enable travis ci to run a pylint for patches? that way it gets captured easily.

Or an easy entry for community members to contribute.

**Comment by sac** [comment]
@s-seitz right. I have fixed it in a subsequent PR here: https://github.com/gluster/gstatus/pull/19/files

**Comment by Apollon77** [comment]
GitHub Action? ;-)

**Comment by sac** [comment]
> @sac is it possible to enable travis ci to run a pylint for patches? that way it gets captured easily.
> 
> Or an easy entry for community members to contribute.

Ack!

**Comment by Apollon77** [comment]
https://github.com/cclauss/GitHub-Action-for-pylint as basis maybe?

**Comment by sac** [comment]
Can someone review: https://github.com/gluster/gstatus/pull/21

**Comment by sac** [comment]
I'll merge it once reviewed.

**Comment by sac** [comment]
Closing the issue, tested with the latest build. Which can be found here: https://copr.fedorainfracloud.org/coprs/sac/gstatus/builds/
