### ISSUE TITLE
Port gstatus to python3

### ISSUE THREAD

**Issue by sac** [gluster/gstatus#23]
Currently works only on python2, prioritize to port to python3.

**Comment by DONCIEUX-CAMILLE** [comment]
Hi.
To migrate to python 3, these are the changes that you must do :
Change all print "" to print ("") in all occurence in the code

in libgluster/cluster.py
@@ -678,8 +677,7 @@
  data = {}
  data_string = ''
- for key, value in sorted(var(self).iteritems()):
+for key, value in sorted(var(self).items()):

in libutils/network.py
@@ -121,17 +121,17 @@
sck = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)

- names = array.array('B', '\0' * __bytes)
+ names = array.array('B', bytearray('\0' * __bytes, 'utf-8'))
  outbytes = struct.unpack('iL', fcntl.ioctl(
     sck.fileno(),
     SIOCGICONF,
     struct.pack('iL', __bytes, names.buffer_info()[0])))[0]

- namestr = names.tostring()
+ namestr = names.tobytes()
+ if_list = [(namestr[i:i + 16].decode('utf-8').split('\0', 1)[0],
+                  socket.inet_ntoa(namestr[i + 20:i + 24]))
+           for i in range(0, outbytes, struct_size)]

- if_list = [(namestr[i:i + 16].split('\0', 1)[0],
-                  socket.inet_ntoa(namestr[i + 20:i + 24]))
-           for i in range(0, outbytes, struct_size)]

in libcommand/glustercmd.py
@@ -106,8 +106,8 @@
                                  preexec_fn=os.setsid)

          stdout, stderr = self.cmdProcess.communicate()
-        self.stdout = stdout.split('\n')[:-1]
-        self.stderr = stderr.split('\n')[:-1]
+       self.stdout = stdout.decode('utf-8').split('\n')[:-1]
+       self.stderr = stderr.decode('utf-8').split('\n')[:-1]

Camille

**Comment by Apollon77** [comment]
Cool. Could you provide a pr?
