### ISSUE TITLE
Feature Req: Quota Info

### ISSUE THREAD

**Issue by B3DTech** [gluster/gstatus#25]
Hi - like the utility and it's being used in a Zabbix monitoring project.  Wondering if it's possible to also pull in the Gluster quota limits on a volume?  Thanks.

**Comment by sac** [comment]
@B3DTech latest fix (PR #29) adds quota and snapshot support. Can you tell us how you were using gstatus? JSON output?

**Comment by sac** [comment]
v1.0.0 fixes the issue. https://github.com/gluster/gstatus/releases/download/v1.0.0/gstatus
