### ISSUE TITLE
json output should not contain any log messages

### ISSUE THREAD

**Issue by mtz29** [gluster/gstatus#56]
When running `gstatus -a -o json` I am getting non-json data.

Here's the example line causing the aforementioned issue:
https://github.com/gluster/gstatus/blob/6cc8935c5380b39f4419321502d9421b3038b2ca/gstatus/glusterlib/cluster.py#L185

It should print notes, errors, etc. to stderr instead of stdout, example:

```
print("error1", file=sys.stderr)
```

**Comment by sac** [comment]
You're right, I'll fix this.

**Comment by mtz29** [comment]
> You're right, I'll fix this.

This should do the job:
```
diff --git a/gstatus/glusterlib/cluster.py b/gstatus/glusterlib/cluster.py
index ee85f73..2b14077 100644
--- a/gstatus/glusterlib/cluster.py
+++ b/gstatus/glusterlib/cluster.py
@@ -1,4 +1,5 @@
 import re
+import sys
 
 from glustercli.cli import peer, quota, volume, snapshot, glusterfs_version, \
     heal
@@ -182,4 +183,4 @@ class Cluster(object):
                     heal_fail = 1
                     pass
         if heal_fail:
-            print("Note: Unable to get self-heal status for one or more volumes")
+            print("Note: Unable to get self-heal status for one or more volumes", file=sys.stderr)
```

I could not raise PR.

**Comment by sac** [comment]
Was there any error?

**Comment by sac** [comment]
I'll fix this and in many other places where we print the error messages.

**Comment by mtz29** [comment]
> Was there any error?

No, just no permissions to raise PR. I think that's limited to contributors only(?). 

> I'll fix this and in many other places where we print the error messages.

Sure.

**Comment by sac** [comment]
No, not at all. It is open to everyone.

This is the process we follow:
0. Fork the project.
1. git clone from your fork
2. Make changes and push to your repository
3. Raise a PR

**Comment by sac** [comment]
https://github.com/gluster/gstatus/pull/57

**Comment by sac** [comment]
Release https://github.com/gluster/gstatus/releases/tag/v1.0.6 fixes the issue.
