### ISSUE TITLE
gstatus is not compatible with this version of glusterfs 4.1

### ISSUE THREAD

**Issue by leeyc0** [gluster/gstatus#9]
The problem is in this line
https://github.com/gluster/gstatus/blob/master/gstatus/libutils/utils.py#L65

The test fails with minor version (0<4) although major version passes (4>3).

It should be rewritted to
```
if (int(this_major) > int(tgt_major)):
    return True
elif (int(this_major) == int(tgt_major)):
    if (int(this_minor) >= int(tgt_minor)):
        return True
    else:
        return False
else:
    return False
```

**Comment by sac** [comment]
@leeyc0 it is not. There is no work going on to support 4.x.

**Comment by leeyc0** [comment]
Oh I see.

**Comment by amarts** [comment]
To give more information, we are planning to make [glusterd2](../../glusterd2) a default with 4.2+, which will provide ReST apis, and it would be used by other monitoring tools to provide you with relevant information. It was harder for us to maintain the --xml based gstatus with fast changing glusterd code. Hope that gives some clarity. @leeyc0
